### ISSUE TITLE
I/O slides link broken

### ISSUE THREAD

**Issue by johnhiott** [gdg-charlotte/talks#11]
Link to I/O slides in readme is broken

**Comment by setheclark** [comment]
@johnhiott Broken how?  It works for me.

**Comment by setheclark** [comment]
@johnhiott Never mind.  It works for me cause I'm signed in to the acct.  Tried in chrome porn-mode and it failed.

**Comment by setheclark** [comment]
...Uploaded but not published.  It should work now.
