### ISSUE TITLE
Request: Architecture Components

### ISSUE THREAD

**Issue by setheclark** [gdg-charlotte/talks#7]
**Talk Request**
- [] Topic
- [] How the new architecture components will make developing Android apps easier
- [] Beginner

**Comment by johnhiott** [comment]
I am woking on something now.

**Comment by johnhiott** [comment]
### Android Architecture Overview

- Intro to:
  - additions for handling lifecycle
  - LiveData
  - ViewModel Room 
  - Room
- will show demo of working app along w/ code

*This will be targeted for July meetup.*

**Comment by setheclark** [comment]
@johnhiott Can you submit a PR for this issue.  Just edit the README to add a link to the github project for the code from your talk.  Also, can you ask Payne to submit a PR for his talk as well?

**Comment by johnhiott** [comment]
Can do.  Thanks.
